# Lint 対象を指定
included:
    - SwiftLintSample/
# Lint 対象から除外する
excluded:
    - SwiftLintSample/T.swift
# 無効にするルール
disabled_rules:
    - file_length
    - trailing_comma
    - trailing_whitespace
    - trailing_newline
    - vertical_whitespace
    - function_body_length
    - type_body_length
    - line_length
    - vertical_parameter_alignment
# 変数などの名前の最低の長さを指定。これより短いと違反となる
# 1 にしておくと、このルールが実質無効となる
identifier_name:
    min_length: 1
# 型名のルールに対しての excluded（除外）
# ここでは lowerCamelClass という型名はルールの検査から除外される
type_name:
    excluded:
      - lowerCamelClass
